import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineConfig } from 'vitest/config';

import { storybookTest } from '@storybook/addon-vitest/vitest-plugin';

import { playwright } from '@vitest/browser-playwright';

const dirname =
  typeof __dirname !== 'undefined' ? __dirname : path.dirname(fileURLToPath(import.meta.url));

const uiDir = path.join(dirname, 'src/components/ui');

/*
 * One test project per primitive, running the same stories.
 *
 * Stories import `@/components/ui/*`, so aliasing that path per project runs the whole
 * suite -- accessibility assertions included -- against each variant's tree. A port that
 * changes focus order, drops an aria attribute or breaks keyboard operation fails in the
 * same assertions that guard Base UI. Writing separate tests per variant would let the
 * variants become separately correct rather than equivalent, which is the opposite of what
 * a design system is for.
 */
const VARIANTS = [
  { id: 'base', dir: null },
  { id: 'radix', dir: path.join(dirname, 'src/variants/radix') },
  { id: 'aria', dir: path.join(dirname, 'src/variants/aria') },
];

/** A component with no primitive import is identical under every variant. */
function primitiveFree(name: string) {
  return !fs.readFileSync(path.join(uiDir, `${name}.tsx`), 'utf8').includes('@base-ui/react');
}

/*
 * Which components a variant may be tested against.
 *
 * Running a story for an UNPORTED component would resolve through the fallback to Base UI
 * and report it as a Radix pass -- coverage that actively lies. A variant runs a story only
 * where it has ported the component, or where the component touches no primitive and the
 * canonical file is genuinely correct for every variant.
 */
function componentsFor(variant: (typeof VARIANTS)[number]) {
  return fs
    .readdirSync(uiDir)
    .filter((file) => file.endsWith('.tsx'))
    .map((file) => file.replace(/\.tsx$/, ''))
    .filter((name) => {
      if (variant.id === 'base') return true;
      if (variant.dir && fs.existsSync(path.join(variant.dir, `${name}.tsx`))) return true;
      return primitiveFree(name);
    });
}

/*
 * A generated Storybook config dir per variant.
 *
 * Vitest's own `test.include` is ignored by the Storybook plugin -- it warns and uses the
 * `stories` field instead -- so restricting a variant to its ported components has to
 * happen in a Storybook config. Generating it here rather than committing it means the
 * list cannot drift from what is actually ported: it is rebuilt every time tests run.
 */
function configDirFor(variant: (typeof VARIANTS)[number]) {
  if (variant.id === 'base') return path.join(dirname, '.storybook');

  const dir = path.join(dirname, `.storybook-${variant.id}`);
  fs.mkdirSync(dir, { recursive: true });

  const stories = componentsFor(variant)
    .map((name) => `../src/stories/${name}.stories.tsx`)
    .filter((rel) => fs.existsSync(path.join(dir, rel)));

  fs.writeFileSync(
    path.join(dir, 'main.ts'),
    `// GENERATED by vitest.config.ts -- do not edit, and do not commit expectations to it.\n` +
      `import type { StorybookConfig } from '@storybook/nextjs-vite';\n\n` +
      `import base from '../.storybook/main';\n\n` +
      `const config: StorybookConfig = {\n` +
      `  ...base,\n` +
      `  stories: ${JSON.stringify(stories, null, 4).replace(/\n/g, '\n  ')},\n` +
      `  staticDirs: ['../public'],\n` +
      `};\n\nexport default config;\n`,
    'utf8'
  );

  // Re-exporting runs the base module, which is what loads globals.css into every story.
  fs.writeFileSync(
    path.join(dir, 'preview.tsx'),
    `// GENERATED by vitest.config.ts -- do not edit.\nexport { default } from '../.storybook/preview';\n`,
    'utf8'
  );

  return dir;
}

/** Resolve `@/components/ui/x` to the variant's file when it has one. */
function variantAlias(variant: (typeof VARIANTS)[number]) {
  if (!variant.dir) return [];
  return [
    {
      find: /^@\/components\/ui\/(.+)$/,
      replacement: '$1',
      customResolver(name: string) {
        const ported = path.join(variant.dir!, `${name}.tsx`);
        return fs.existsSync(ported) ? ported : path.join(uiDir, `${name}.tsx`);
      },
    },
  ];
}

export default defineConfig({
  test: {
    projects: VARIANTS.map((variant) => ({
      extends: true,
      plugins: [storybookTest({ configDir: configDirFor(variant) })],
      resolve: { alias: variantAlias(variant) },
      test: {
        name: variant.id === 'base' ? 'storybook' : `storybook-${variant.id}`,
        browser: {
          enabled: true,
          headless: true,
          provider: playwright({}),
          instances: [{ browser: 'chromium' }],
        },
      },
    })),
  },
});
